import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "2": "تخطي",
          "3": "متابعة",
          "4": "تسجيل دخول",
          "5": "أدخل رقم الجوال للتسجيل أو الدخول",
          "6": "رقم جوالك",
          "7": "التسجيل عبر التواصل الاجتماعي",
          "8": "ليس لديك حساب ؟",
          "9": "إنشاء حساب",
          "10": "رمز التحقق",
          "11": "أدخل الرمز المكون من 4 أرقام المرسل إليك على",
          "12": "لم يصلني الرمز",
          "13": "إعادة إرسال",
          "14": "تحقق",
          "15": "مستخدم",
          "16": "شراء وبيع وتأجير معدات التصوير",
          "17": "فنان",
          "18": "تقديم خدمات ومساعدة المحترفين",
          "19": 'الاسم الأول',
          "20": 'الاسم الأخير',
          "21": "البريد الالكتروني",
          "22": 'رقم الجوال',
          "23": 'الدول',
          "24": 'المدن',
          "25": 'قم بتعبئة بياناتك',
          "26": 'أوافق على ',
          "27": 'الشروط والأحكام',
          "28": "تأكيد",
          "29": "نعم",
          "30": "لا",
          "31": 'هل أنت متأكد أنك تريد الخروج؟',
          "32": "الأكبر والأكثر ثقة",
          "33": "مجتمع مشاركة معدات التصوير",
          "34": "تأجير",
          "35": "شراء",
          "36": "اعثر على معدات التصوير",
          "37": "بحث",
          "38": "تصفح خدمتنا",
          "39": "الإيجار",
          "40": "البيع والشراء",
          "41": "الخدمات",
          "42": "مواقع التصوير",
          "43": "تصفح الفئات",
          "44": "عرض الكل",
          "45": "المنتجات الرائجة للإيجار",
          "46": "المدرجة حديثاً للإيجار",
          "47": "المنتجات الرائجة للبيع",
          "48": "المدرجة حديثاً للبيع",
          "49": "أبرز الفنانين",
          "50": "أحدث مواقع التصوير",
          "51": "إنتاج المحترفين",
          "52": "بحث بالفئات",
          "53": "بحث عن فنانين",
          "54": "تصفية",
          "55": "ترتيب",
          "56": "فلترة",
          "57": "حسب العمر",
          "58": "مميزات",
          "59": "أحدث الاصدارات",
          "60": "الأكثر مبيعا",
          "61": "الأكثر مشاهدة",
          "62": "حسب السعر",
          "63": "من الأعلى",
          "64": "من الأقل",
          "65": "ترتيب حسب",
          "66": "من الأحدث",
          "67": "ترتيب أبجدي",
          "68": "من أ - ي",
          "69": "من ي - أ",
          "70": "من الأقدم",
          "71": "بحث عن المنتجات",
          "72": "معدات الصوت",
          "73": "شراء الآن",
          "74": "الموقع على الخريطة",
          "75": "الناشر",
          "76": "شراء منتج",
          "77": "عنوان التوصيل",
          "78": "تغيير",
          "79": "إضافة كود خصم",
          "80": "طريقة الدفع",
          "81": "الفاتورة",
          "82": "المنتجات",
          "83": "خصومات متعددة الأيام",
          "84": "العمولة",
          "85": "التوصيل",
          "86": "الإجمالي",
          "87": "دفع",
          "88": "تم الدفع والشراء بنجاح",
          "89": "يمكنك مشاهدة وتتبع طلبك ",
          "90": "رقم الطلب",
          "91": "الوقت",
          "92": "تاريخ الشراء",
          "93": "تتبع الطلب",
          "94": "الرئيسية",
          "95": "إضافة إلى السلة",
          "96": "الملخص",
          "97": "سعر الإيجار",
          "99": "حفظ وإضافة",
          "100": "ملخص الإيجار",
          "101": "تم إضافة إلى السلة بنجاح",
          "102": "عرض السلة",
          "103": "إزالة",
          "104": "موافق",
          "105": "إقرار وتعهد",
          "106": "بين",
          "107": "مدة الإيجار",
          "108": "من",
          "109": "إلى",
          "110": "بالنقر على متابعة",
          "111": "فإنك تقر وتتعهد بأنك قد قرأت الشروط",
          "112": "سيتم حفظ الإقرار مع الطلب",
          "113": "تأجير المنتجات",
          "114": "كود الخصم",
          "115": "تطبيق",
          "116": "تم تطبيق كود الخصم بنجاح",
          "117": "إضافة عنوان",
          "118": "إفتراضي",
          "119": "اعثر على معدات التصوير",
          "120": "اعثر على ما تريد مع إنتاجي",
          "121": "سجل البحث",
          "122": "مسح الكل",
          "123": "نتائج البحث",
          "124": "أنجز عملك مع المبدعين",
          "125": "بحث عن خدمة",
          "126": "إخراج",
          "127": "عقد",
          "128": "جديد",
          "129": "يبدء",
          "130": "مميز",
          "131": "ينتهى",
          "132": "مدة العمل",
          "133": "قدم الآن",
          "134": "الفنانين",
          "135": "تغيير المدينة",
          "136": "بحث عن المدينة",
          "137": "أكتب هنا ...",
          "138": "تواصل",
          "139": "مراجعات إيجابية",
          "140": "الاستجابة",
          "141": "عضو",
          "142": "نبذة",
          "143": "المعرض",
          "144": "المنتجات",
          "145": "الدورات",
          "146": "شاهد العمل",
          "147": "المراجعات",
          "148": "الموقع",
          "149": "الصور",
          "150": "الفيديوهات",
          "151": "تفاصيل الدورة",
          "152": "فيديوهات الدورة",
          "153": "تم الشراء",
          "154": "مواقع تصوير احترافية",
          "155": "بحث مواقع التصوير",
          "156": "اعثر على معدات التصوير",
          "157": "مستخدم",
          "158": "الملف الشخصي",
          "159": "الإشعارات",
          "160": "المحادثات",
          "161": "الطلبات",
          "162": "باقات الاشتراك",
          "163": "إضافة منتج أو خدمة",
          "164": "المفضلة",
          "165": "عناوين التوصيل",
          "166": "اتصل بنا",
          "167": "عن التطبيق",
          "168": "اللغة",
          "169": "الإعدادات",
          "170": "تسجيل خروج",
          "171": "المنتج",
          "172": "إرسال",
          "173": "الحالة",
          "174": "إعادة تعيين",
          "175": "محترف",
          "176": "مؤجر",
          "177": "مستخدم",
          "178": "مستأجر",
          "179": "مشتري",
          "180": "بائع",
          "181": "منتجات",
          "182": "مواقع",
          "183": "خدمة",
          "184": "اليوم",
          "185": "تتبع الطلب",
          "186": "تم الطلب",
          "187": "قيد التنفيذ",
          "188": "مكتمل",
          "189": "الدعم الفني",
          "190": "إذا كان لديك أي استفسارات ، اتصل بالدعم",
          "191": "الدعم المباشر",
          "192": "إلغاء الطلب",
          "193": "يمكنك الغاء الطلب في حال عدم الرد او وجود مشكلة",
          "194": "هل تريد إلغاء الطلب ؟",
          "195": "لا يمكن التراجع عن هذه الخطوة",
          "196": "نعم ، إلغاء الطلب",
          "197": "تعديل عنوان التوصيل",
          "198": "العنوان",
          "199": "الدولة",
          "200": "المدينة",
          "201": "الموقع على الخريطة",
          "202": "تعيين كعنوان افتراضي",
          "203": "حفظ",
          "204": "حذف",
          "205": "ملفي الشخصي",
          "206": "معرض الأعمال",
          "207": "إعدادات الحساب",
          "208": "تعديل",
          "209": "المهارات",
          "210": "الفيديو التعريفي",
          "211": "إكمال ملفي الشخصي",
          "212": "أضف صورة الغلاف",
          "213": "التخصص",
          "214": "إضافة الفيديو",
          "215": "اختيار",
          "216": "بحث عن تخصص",
          "217": "بحث عن المهارات",
          "218": "التحقق من الهوية الشخصية",
          "219": "أضف صورة الهوية",
          "220": "حفظ التعديلات",
          "221": "إضافة عمل جديد",
          "222": "إضافة جديد",
          "223": "أضف صور",
          "224": "عنوان الفيديو",
          "225": "أدخل عنوان الفيديو",
          "226": "حذف العمل",
          "227": "هل تريد حذف هذا العمل ؟",
          "228": "نعم ، حذف",
          "229": "الإشعارات التسويقية",
          "230": "سياسة الخصوصية",
          "231": "حذف حسابي",
          "232": "ماذا ستفقد إذا طلبت حذف حسابك",
          "233": "ستفقد جميع أنواع المحتوى والبيانات الواردة في هذا الحساب :",
          "234": "حسابي",
          "235": "سجل الشراء",
          "236": "حق الوصول إلى التطبيق",
          "237": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة",
          "238": "هل أنت متأكد من حذف حسابك ؟",
          "239": "نعم ، حذف حسابي",
          "240": "العربية",
          "241": "الإنجليزية",
          "242": "وسائل التواصل الاجتماعي",
          "243": "إذا كان لديك أي استفسارات ، اتصل بالدعم",
          "244": "تواصل معنا",
          "245": "إذا كانت لديك مشكلة مع الطلبات أو أشياء أخرى",
          "246": "إرسال رسالة",
          "247": "الاسم كامل",
          "248": "الاسم",
          "249": "الرسالة",
          "250": "المرفقات",
          "251": "إختياري",
          "252": "تم إرسال رسالتك بنجاح",
          "253": "إضافة منتج ",
          "254": "إضافة موقع ",
          "255": "إضافة خدمة ",
          "256": "إضافة دورات ",
          "257": "إضافة منتج جديد",
          "258": "بيع",
          "259": "اسم المنتج",
          "260": "السعر",
          "261": "ادخل  سعر إيجار اليوم",
          "262": "أدخل السعر",
          "263": "ر.س/يوم",
          "264": "التصنيف الأساسي",
          "265": "اختر",
          "266": "التصنيف الفرعي",
          "267": "اختر الموقع",
          "268": "التفاصيل",
          "269": "هل تريد تفعيل خصم متعدد الأيام بنسبة 20% ؟",
          "270": "إضافة المواصفات",
          "271": "أضف جديد",
          "272": "المواصفات",
          "273": "بحث عن تصنيف",
          "274": "صور المنتج",
          "275": "نشر",
          "276": "تم إضافة منتج جديد بنجاح",
          "277": "يمكنك عرض المنتج أو إضافة المزيد",
          "278": "عرض المنتج",
          "279": "إضافة منتج جديد",
          "280": "صور الموقع",
          "281": "اسم الموقع",
          "282": "التصنيف",
          "283": "اسم الخدمة",
          "284": "حالة العمل",
          "285": "عقد",
          "286": "سعر ثابت",
          "287": "بالساعة",
          "288": "سعر الخدمة",
          "289": "أدخل السعر",
          "290": "مدة العقد",
          "291": "اختر التاريخ",
          "292": "المدينة",
          "293": "اختر المدينة",
          "294": "بحث عن المدينة",
          "295": "اسم الدورة",
          "296": "سعر الدورة",
          "297": "ر.س",
          "298": "مقدمة عن الدورة",
          "299": "أضف فيديو المقدمة",
          "300": "يمكن مشاهدته قبل الشراء",
          "301": "تم تحميل",
          "302": "أضف فيديوهات الدورة",
          "303": "حذف المنتج",
          "304": "هل تريد حذف المنتج ؟",
          "305": "لا يوجد عنواني محفوظة",
          "306": "إضافة عنوان جديد",
          "307": "إضافة عنوان",
          "308": "بحث عن مكان",
          "309": "اختر الدولة",
          "310": "أدخل العنوان",
          "311": "المحترفين",
          "312": "احصل على باقة الاشتراك المناسبة لك",
          "313": "أساسي",
          "314": "مجاني",
          "315": "رفع المنتجات بجودة 1080P",
          "316": "رفع محددة بـ 3 منتجات في كل قسم",
          "317": "قطع نسبه 20% من البيع",
          "318": "مشترك",
          "319": "المحترفين",
          "321": "رفع المنتجات بجودة 4k",
          "322": "رفع 50 منتج في كل قسم",
          "323": "قطع نسبه 15% من البيع",
          "324": "اشتراك",
          "325": "VIP",
          "326": "إضافة منتجات غير محدودة",
          "327": "توثيق الحساب",
          "328": "خدمة العملاء",
          "329": "تجهيز الحساب كامل من تصاميم ورفع المنتجات",
          "330": "إضافة إعلانات مجاناً أسبوعياً",
          "331": "شراء الباقة",
          "332": "سعر الباقة",
          "333": "تم الدفع والاشتراك بنجاح",
          "334": "باقة المحترفين",
          "335": "تاريخ الاشتراك",
          "336": "منتج",
          "337": "لا يوجد انترنت",
          "338": "عنصر",
          "339": "لا يوجد بيانات بعد ",
          "340": "تعديل المنتج",
          "341": "اضغط لتعديل الصور",
          "342": "صور الموقع",
          "343": "تعديل الموقع",
          //صور الموقع

          //"أدخل رقم الجوال للتسجيل أو الدخول",
        },
        "en": {
          "2": "Skip",
          "3": "Continuation",
          "4": "Login",
          "5": "Enter the mobile number to register or login",
          "6": "Mobile number",
          "7": "Register via social networking",
          "8": "Don't have an account?",
          "9": "Create an account",
          "10": "verification code",
          "11": "Enter the 4-digit code sent to you at",
          "12": "I did not receive the code",
          "13": "Resend",
          "14": "verification",
          "15": "user",
          "16": "Buying, selling and renting photographic equipment",
          "17": "artist",
          "18": "Providing professional services and assistance",
          "19": 'First Name',
          "20": 'last name',
          "21": "Email",
          "22": 'Mobile number',
          "23": 'Countries',
          "24": 'City',
          "25": 'Fill in your data',
          "26": 'I agree to',
          "27": 'Terms and Conditions',
          "28": "Confirm",
          "29": "Yes",
          "30": "No",
          "31": "Are you sure you want to exit?",
          "32": "The biggest and most trusted",
          "33": "Photography equipment sharing community",
          "34": "Leasing",
          "35": "buying",
          "36": "Find photography equipment",
          "37": "research",
          "38": "Browse our service",
          "39": "rent",
          "40": "Buying and selling",
          "41": "Services",
          "42": "Filming locations",
          "43": "Browse categories",
          "44": "view all",
          "45": "Popular products for rent",
          "46": "Newly listed for rent",
          "47": "popular products for sale",
          "48": "Newly listed for sale",
          "49": "The most prominent artists",
          "50": "Latest filming locations",
          "51": "PRO PRODUCTION",
          "52": "search by categories",
          "53": "Search for artists",
          "54": "filtering",
          "55": "ranking",
          "56": "Filter",
          "57": "by age",
          "58": "features",
          "59": "Latest releases",
          "60": "best seller",
          "61": "most watched",
          "62": "According to the price",
          "63": "From the top",
          "64": "who least",
          "65": "sort by",
          "66": "of the newest",
          "67": "Alphabetical order",
          "68": "from A-Z",
          "69": "from Z-A",
          "70": "from the oldest",
          "71": "Search for products",
          "72": "sound Equipment",
          "73": "buy now",
          "74": "Location on the map",
          "75": "publisher",
          "76": "Buy a product",
          "77": "Delivery Address",
          "78": "changing",
          "79": "Add a discount code",
          "80": "payment method",
          "81": "Bill",
          "82": "products",
          "83": "Multi-day discounts",
          "84": "commission",
          "85": "delivery",
          "86": "Total",
          "87": "pay",
          "88": "Payment and purchase completed successfully",
          "89": "You can view and track your order",
          "90": "order number",
          "91": "the time",
          "92": "The date of purchase",
          "93": "order tracking",
          "94": "Main",
          "95": "Add to cart",
          "96": "Summary",
          "97": "rental price",
          "99": "Save and add",
          "100": "Rental summary",
          "101": 'New has been added successfully',
          "102": "View cart",
          "103": "Removal",
          "104": "acceptable",
          "105": "Acknowledgment and commitment",
          "106": "between",
          "107": "lease term",
          "108": "from",
          "109": "to",
          "110": "By clicking Continue",
          "111": "You represent and warrant that you have read the Terms",
          "112": "The declaration will be saved with the application",
          "113": "Product rental",
          "114": "discount code",
          "115": "application",
          "116": "The discount code has been applied successfully",
          "117": "add address",
          "118": "hypothetical",
          "119": "Find photography equipment",
          "120": "Find what you want with Intaji",
          "121": "search history",
          "122": "clear all",
          "123": "research results",
          "124": "Do your work with creators",
          "125": "Search for a service",
          "126": "Directed by",
          "127": "a contract",
          "128": "new",
          "129": "starts",
          "130": "distinct",
          "131": "finish",
          "132": "Duration of employment",
          "133": "Apply now",
          "134": "artists",
          "135": "City change",
          "136": "City search",
          "137": "Write here...",
          "138": "communication",
          "139": "Positive reviews",
          "140": "response",
          "141": "member",
          "142": "Brief",
          "143": "exhibition",
          "144": "products",
          "145": "Courses",
          "146": "Watch the action",
          "147": "reviews",
          "148": "the site",
          "149": "the pictures",
          "150": "videos",
          "151": "Course details",
          "152": "Course videos",
          "153": "Buying succeeded",
          "154": "Professional photography sites",
          "155": "Filming locations search",
          "156": "Find photography equipment",
          "157": "user",
          "158": "Profile personly",
          "159": "Notices",
          "160": "conversations",
          "161": "Requests",
          "162": "Subscription packages",
          "163": "Add a product or service",
          "164": "Favorite",
          "165": "Delivery addresses",
          "166": "call us",
          "167": "About the application",
          "168": "the language",
          "169": "Settings",
          "170": "Log out",
          "171": "the product",
          "172": "send",
          "173": "the condition",
          "174": "Reset",
          "175": "professional",
          "176": "rented",
          "177": "user",
          "178": "tenant",
          "179": "Buyer",
          "180": "vendor",
          "181": "products",
          "182": "sites",
          "183": "service",
          "184": "Today",
          "185": "order tracking",
          "186": "request is done",
          "187": "Underway",
          "188": "complete",
          "189": "technical support",
          "190": "If you have any questions, contact support",
          "191": "Live support",
          "192": "Cancelling order",
          "193":
              "You can cancel the request if there is no response or if there is a problem",
          "194": "Do you want to cancel the order?",
          "195": "This step cannot be undone",
          "196": "Yes, cancel the order",
          "197": "Modify the delivery address",
          "198": "the address",
          "199": "Country",
          "200": "City",
          "201": "Location on the map",
          "202": "Set as default address",
          "203": "save",
          "204": "delete",
          "205": "my personal file",
          "206": "Business fair",
          "207": "account settings",
          "208": "Edit",
          "209": "skills",
          "210": "Introductory video",
          "211": "Complete my profile",
          "212": "Add a cover photo",
          "213": "Specialization",
          "214": "add video",
          "215": "to choose",
          "216": "Search for a specialty",
          "217": "Search for skills",
          "218": "Personal identity verification",
          "219": "Add a photo ID",
          "220": "Save modifications",
          "221": "Add a new job",
          "222": "add new",
          "223": "Add photos",
          "224": "video address",
          "225": "Enter the title of the video",
          "226": "delete work",
          "227": "Do you want to delete this work?",
          "228": "Yes, delete",
          "229": "Marketing notices",
          "230": "privacy policy",
          "231": "Delete My Account",
          "232": "What will you lose if you request deletion of your account",
          "233":
              "You will lose all types of content and data contained in this account:",
          "234": "My account",
          "235": "purchase history",
          "236": "The right to access the application",
          "237":
              "This text is an example of text that can be replaced in the same space",
          "238": "Are you sure to delete your account?",
          "239": "Yes, delete my account",
          "240": "Arabic",
          "241": "English",
          "242": "Social media",
          "243": "If you have any questions, contact support",
          "244": "Connect with us",
          "245": "If you have a problem with orders or other things",
          "246": "Sending a Message",
          "247": "Full Name",
          "248": "the name",
          "249": "the message",
          "250": "attachments",
          "251": "my choice",
          "252": "Your message was sent successfully",
          "253": "Add a product",
          "254": "Add a site",
          "255": "Add a service",
          "256": "Add courses",
          "257": "Add a new product",
          "258": "sale",
          "259": "product name",
          "260": "the price",
          "261": "Enter today's rental price",
          "262": "Enter the price",
          "263": "R.S/day",
          "264": "Basic classification",
          "265": "Choose",
          "266": "subcategory",
          "267": "Choose the location",
          "268": "the details",
          "269": "Do you want to activate a multi-day discount of 20%?",
          "270": "Add specifications",
          "271": "add new",
          "272": "Specifications",
          "273": "Search for a rating",
          "274": "Product pictures",
          "275": "to publish",
          "276": "A new product has been added successfully",
          "277": "You can view the product or add more",
          "278": "Product Show",
          "279": "Add a new product",
          "280": "Website photos",
          "281": "Web site name",
          "282": "Category",
          "283": "Service name",
          "284": "working condition",
          "285": "a contract",
          "286": "Fixed price",
          "287": "per hour",
          "288": "Service price",
          "289": "Enter the price",
          "290": "Duration of the contract",
          "291": "Choose the date",
          "292": "City",
          "293": "Select the city",
          "294": "City search",
          "295": "Course name",
          "296": "Course price",
          "297": "R.S",
          "298": "Introduction to the course",
          "299": "Add your introduction video",
          "300": "View it before purchasing",
          "301": "download complete",
          "302": "Add course videos",
          "303": "Delete the product",
          "304": "Do you want to delete the product?",
          "305": "My address is not reserved",
          "306": "Add a new address",
          "307": "add address",
          "308": "Find a place",
          "309": "Select the country",
          "310": "Enter the address",
          "311": "professionals",
          "312": "Get the right subscription package for you",
          "313": "Basic",
          "314": "Complimentary",
          "315": "Uploading products in 1080P quality",
          "316": "Upload a maximum of 3 products in each category",
          "317": "Cut 20% of sales",
          "318": "Subscriber",
          "319": "Professionals",
          "321": "Uploading products in 4k quality",
          "322": "Upload 50 products in each category",
          "323": "Cut 15% of sales",
          "324": "Subscription",
          "325": "VIP",
          "326": "Add unlimited products",
          "327": "Account verification",
          "328": "Customer service",
          "329":
              "Complete account setup, including designs and product uploads",
          "330": "Add free advertisements weekly",
          "331": "Package purchase",
          "332": "Package price",
          "333": "Payment and subscription were successful",
          "334": "Professionals package",
          "335": "Subscription date",
          "336": "product",
          "337": "there is no Internet",
          "338": "element",
          "339": "There is no data yet",
          "340": "Product Modification",
          "341": "Click to edit photos",
          "342": "Pictures of the site",
          "343": "Modify the site",
          // تم إرسال رسالتك بنجاح
        }
      };
}
//search history

